version: '3'
services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-12-may-2020/final-projects/technical-interview-platform/technical-challenge-app:latest
    env_file:
      - ./env/dev.env
    command: 'python manage.py runserver 0:8000'
    ports:
    - 8000:8000
    volumes:
    - ./backend:/backend

    depends_on:
      - db

  db:
    image: postgres:11
    env_file:
      - ./env/dev.env
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_db:
